### ISSUE TITLE
Task: Create user stories

### ISSUE THREAD

**Issue by Iwuh** [imran1289-ah/team_Taiga-soen341project2022#2]
During this sprint, we must write 4 user stories for core features that will be implemented next sprint. This issue will be closed once all 4 have been written. Feel free to discuss what kind of user stories we'd like to begin with.

**Comment by imran1289-ah** [comment]
We need to add our last story, and I am not sure what you guys want to add. I was thinking about delivery companies who will be able to see products that are purchased by users and that need to be shipped to them. So basically, "As a delivery company user (or whatever makes sense), I want to be able to see all the products that have been purchased by customers so that I can ship the products to their home

**Comment by Iwuh** [comment]
I feel like the fourth user story could be something about searching the catalogue of items on the site.
